### PR TITLE
Fix for overlapping generations. 

### PR DESCRIPTION
**Pull request by molpopgen**

### CODE REVIEW

**Comment by molpopgen** [comment]
This is wrong, but perhaps on the right track.  What I've done here is not throw out individuals descending from alive individuals.  That's not the same as removing segments from alive individuals that were transmitted to dead individuals passing on no segments.

**Comment by molpopgen** [comment]
I think we need an individuals list consisting of a live individuals containing segments. Then we simplify over that list and the dead individuals. These notes are taken while walking the dog and thus the quality cannot be guaranteed.

Edit: not quite this simple.  A naive approach processes individuals out of order with respect to birth time.

**Comment by jeromekelleher** [comment]
Ah yes, that makes sense.

**Comment by molpopgen** [comment]
Notes for the weekend: getting closer.  
5c4f153   results in duplicate edges for overlapping generations, though.

The duplicate edges arise from double-adding to children of older nodes w/multiple segments.  Arg.

**Comment by molpopgen** [comment]
@jeromekelleher -- I got the overlapping generations fixed, I think.  There's a refactor of the simulation logic itself, with all individuals now in one list.  To keep alive and dead individuals really separate would require co-iteration in such a way that you'd co-traverse in the right birth order.  We can revisit that.

The tricky bit was figuring out where duplicate edges were arising w/overlapping generations, and you'll see how I solved it in the new `A[ind].append(...)` bit.

If this is merge-able, I can squash it down to one commit.

**Comment by jeromekelleher** [comment]
Thanks @molpopgen, this is good progress. Your method is better all right, since we can just save the individuals by order of birth time and don't need a separate dead list.

**Pull request merged**
